# Generated by Django 6.0.3 on 2026-03-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер кімнати')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за ніч')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний (доступний для броні)')),
                ('image', models.ImageField(blank=True, upload_to='rooms/', verbose_name='Фото номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заїзду')),
                ('check_out', models.DateField(verbose_name='Дата виїзду')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
            },
        ),
    ]
