# Generated by Django 6.0.3 on 2026-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість ліжок'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=True, verbose_name='Кондиціонер'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_bath',
            field=models.BooleanField(default=True, verbose_name='Наявність ванни'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True, verbose_name='Телевізор'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True, verbose_name='Безкоштовний Wi-Fi'),
        ),
        migrations.AddField(
            model_name='room',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 зірка'), (2, '2 зірки'), (3, '3 зірки'), (4, '4 зірки'), (5, '5 зірок')], default=5, verbose_name='Кількість зірок'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер кімнати'),
        ),
    ]
