# Generated by Django 6.0.3 on 2026-03-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_beds_count_room_has_ac_room_has_bath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_fridge',
            field=models.BooleanField(default=False, verbose_name='Холодильник'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kettle',
            field=models.BooleanField(default=True, verbose_name='Електрочайник'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_info',
            field=models.CharField(blank=True, help_text='Наприклад: 750/800/850 для 1/2/3 осіб', max_length=255, verbose_name='Деталі цін'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість ліжек'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='Вентилятор/Кондиціонер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_bath',
            field=models.BooleanField(default=False, verbose_name='Власний санвузол'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='Телевізор'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms/', verbose_name='Головне фото номера'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=70, unique=True, verbose_name='Номер кімнати'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна за ніч'),
        ),
        migrations.AlterField(
            model_name='room',
            name='stars',
            field=models.IntegerField(choices=[(0, 'Без зірок'), (1, '1 зірка'), (2, '2 зірки'), (3, '3 зірки'), (4, '4 зірки'), (5, '5 зірок')], default=0, verbose_name='Кількість зірок'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='Додаткове фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Галерея фото',
            },
        ),
    ]
