# Generated by Django 6.0.3 on 2026-04-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_has_fridge_room_has_kettle_room_price_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_info',
        ),
        migrations.RemoveField(
            model_name='room',
            name='stars',
        ),
        migrations.AlterField(
            model_name='room',
            name='beds_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість ліжок'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=70, unique=True, verbose_name='Назва або номер кімнати'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса (slug)'),
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Кількість осіб')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.room', verbose_name='Кімната')),
            ],
            options={
                'verbose_name': 'Ціна за кількість осіб',
                'verbose_name_plural': 'Динамічні ціни',
                'ordering': ['guests_count'],
                'unique_together': {('room', 'guests_count')},
            },
        ),
    ]
