# Generated by Django 6.0.3 on 2026-04-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_price_per_night_room_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('admin_note', models.TextField(blank=True, verbose_name='Нотатки адміністратора (нюанси/репутація)')),
            ],
            options={
                'verbose_name': 'Профіль клієнта',
                'verbose_name_plural': 'Історія та Клієнти',
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Підтверджене бронювання', 'verbose_name_plural': 'Журнал бронювань'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар до цієї броні'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_confirmed', to='main.room', verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name="Ім'я та Прізвище")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('check_in', models.DateField(verbose_name='Дата заїзду')),
                ('check_out', models.DateField(verbose_name='Дата виїзду')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення/Побажання')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено (Перенесено в бронь)'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Запит на бронювання',
                'verbose_name_plural': 'Запити на бронювання',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customerprofile', verbose_name='Клієнт'),
        ),
    ]
