# Generated by Django 6.0.3 on 2026-04-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customerprofile_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
