# Generated by Django 6.0.3 on 2026-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-check_in'], 'verbose_name': 'Підтверджене бронювання', 'verbose_name_plural': 'Журнал бронювань'},
        ),
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запит на бронювання', 'verbose_name_plural': 'Запити на бронювання'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номери'},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='main_bookin_check_i_5a197e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='main_bookin_room_id_c7a04c_idx'),
        ),
    ]
