# Generated by Django 6.0.3 on 2026-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_booking_options_alter_bookingrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запиту')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Запит на дзвінок',
                'verbose_name_plural': 'Запити на дзвінки',
                'ordering': ['-created_at'],
            },
        ),
    ]
