# Generated by Django 6.0.3 on 2026-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість осіб'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='guests_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість осіб'),
        ),
    ]
