# Generated by Django 6.0.3 on 2026-04-26 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_booking_guests_count_bookingrequest_guests_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути в форматі: '+999999999'. Тільки цифри.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
